### ISSUE TITLE
Keep intermediary counter in a separate file

### ISSUE THREAD

**Issue by liach** [FabricMC/stitch#24]
Mojang currently publishes versions in a non-linear way (combat builds). This has caused some troubles for linear number tracking systems, e.g. mojang dfu versions and intermediary max counters.

Mojang handles its potential dfu version conflicts by bumping data versions aggressively and resorting counters for potential versions. However, we shouldn't take this approach for intermediary counters as we are not aware of the number of fields/methods/classes mojang would add and don't want counters to explode.

I propose to allow keeping track of counters in a separate file (like bfs visit order for a graph structure). this can always guarantee that two versions in a repo which have no direct relationship (i.e. one is not the predecessor of the other) won't have id clashes if the counter is properly stored/read from that separate file in the repo.

**Comment by coderbot16** [comment]
I think this is an issue with intermediary counters in general. There's no way to go back in time (think making intermediaries for 1.12 and below)

**Comment by liach** [comment]
Done already
